#!/bin/sh

if command -v pamixer &>/dev/null; then
    if [ true == $(pamixer --get-mute) ]; then
        echo 0
        exit
    else
		amixer sget Master | grep -oP '(?<=\[)(\d+)'
    fi
else
	amixer sget Master | grep -oP '(?<=\[)(\d+)'
fi
